platform :ios, '8.0'
inhibit_all_warnings!

def pods
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'IQKeyboardManager', '~> 4.0.8'
    pod 'BaiduMapKit', '~> 3.3.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'TTCounterLabel', '~> 1.2.0'
    pod 'FMDBHelper', '~> 0.2.0'
    pod 'SDAutoLayout', '~> 2.1.8'
    pod 'Bugly', '~> 2.4.6'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'iCarousel', '~> 1.8.3'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'YYText', '~> 1.0.7'
    pod 'YYImage', '~> 1.0.4'
    pod 'FLAnimatedImage', '~> 1.0.12'
   
    pod 'SYPhotoBrowser', '~> 2.2'
end
target ‘yanyan’ do
    pods
end
